import type { Metadata } from 'next'
import { Inter, Noto_Sans_Thai } from 'next/font/google'
// import { GeistSans } from 'geist/font/sans'
import './globals.css'
import { ThemeProvider } from '@/components/Themeprovider'
import SessionProvider from '@/components/SessionProvider'
import { getServerSession } from 'next-auth'
import { Toaster } from 'react-hot-toast'
import Footer from '@/components/Footer'
import { NavigationBar } from '@/components/Navbar'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
})

const notoSans = Noto_Sans_Thai({
  variable: '--font-noto-sans-thai',
  subsets: ['thai'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Quaso',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  return (
    <html
      lang="th"
      className={`${inter.variable} ${notoSans.variable}`}
      suppressHydrationWarning
    >
      <body>
        <SessionProvider session={session}>
          <Toaster />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            disableTransitionOnChange
          >
            <main className="flex flex-col h-screen antialiased bg-background">
              <NavigationBar />
              {children}
              <Footer />
            </main>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
