import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { GeistSans } from 'geist/font/sans'
import './globals.css'
import { ThemeProvider } from '../components/Themeprovider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Grader',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <div className="flex flex-col min-h-screen bg-background antialiased">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
